apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentnginx
  labels:
    app: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: podnginx
      labels:
        app: nginx
    spec:
      containers:
        - name: containernginx
          image: nginx
  selector:
    matchLabels:
      app: nginx